# Generated by Django 2.0 on 2019-08-18 09:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='科目名')),
                ('decs', models.CharField(default='', max_length=500, verbose_name='科目说明')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('nianji', models.CharField(choices=[('yinianji', '一年级'), ('ernianji', '二年级'), ('sannianji', '三年级')], max_length=50, verbose_name='年级')),
            ],
            options={
                'verbose_name': '考试科目',
                'verbose_name_plural': '考试科目',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='知识点名')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shijuan.CourseList', verbose_name='所属科目')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shijuan.CourseList', verbose_name='所属课程')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shijuan.Knowledge', verbose_name='所属知识点')),
            ],
            options={
                'verbose_name': '试题列表',
                'verbose_name_plural': '试题列表',
            },
        ),
        migrations.CreateModel(
            name='PaperCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField(verbose_name='题目')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '试题临时列表',
                'verbose_name_plural': '试题临时列表',
            },
        ),
        migrations.CreateModel(
            name='PaperList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='试卷名')),
                ('is_allow', models.BooleanField(default=False, verbose_name='是否启用')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shijuan.CourseList', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '试卷列表',
                'verbose_name_plural': '试卷列表',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(choices=[('xz', '选择题'), ('pd', '判断题'), ('dxt', '多选题')], default='xz', max_length=4, verbose_name='题目类型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('answer', models.TextField(verbose_name='正确答案')),
                ('choice_a', models.TextField(default='A.', verbose_name='A选项')),
                ('choice_b', models.TextField(default='B.', verbose_name='B选项')),
                ('choice_c', models.TextField(default='C.', verbose_name='C选项')),
                ('choice_d', models.TextField(default='D.', verbose_name='D选项')),
                ('choice_e', models.TextField(default='E.', verbose_name='E选项')),
                ('choice_f', models.TextField(default='F.', verbose_name='F选项')),
                ('score', models.IntegerField(default=0, verbose_name='分值')),
                ('jiexi', models.TextField(default='', verbose_name='答案解析')),
                ('note', models.TextField(default='问答题在此处做答', verbose_name='备注信息')),
                ('boolt', models.TextField(default='对', verbose_name='判断正误正确选项')),
                ('boolf', models.TextField(default='错', verbose_name='判断正误错误选项')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('choice_num', models.IntegerField(default=4, verbose_name='选项数')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shijuan.CourseList', verbose_name='考试科目')),
                ('knowledge', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shijuan.Knowledge', verbose_name='所属知识点')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shijuan.PaperList', verbose_name='试卷名称'),
        ),
        migrations.AddField(
            model_name='paper',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shijuan.Question', verbose_name='题目'),
        ),
    ]
