# Generated by Django 2.0 on 2019-08-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shijuan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledge',
            options={'verbose_name': '知识点', 'verbose_name_plural': '知识点'},
        ),
    ]
