# Generated by Django 2.0 on 2019-08-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shijuan', '0002_auto_20190821_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cuoti',
            field=models.CharField(choices=[('zc', '做错'), ('mzg', '没做过'), ('mzc', '没做错')], default='mzg', max_length=10, verbose_name='是否做错'),
        ),
    ]
