# Generated by Django 2.0 on 2019-12-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fenxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie',
            new_name='vedio',
        ),
    ]
