# Generated by Django 2.0 on 2019-08-21 08:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shijuan', '0002_auto_20190821_1648'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='用户答案')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='作答时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shijuan.CourseList', verbose_name='课程')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shijuan.Paper', verbose_name='试卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户做题记录',
                'verbose_name': '用户做题记录',
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='总分')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='录入时间')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('leibie', models.CharField(default='', max_length=50, verbose_name='类别')),
                ('danwei', models.CharField(default='', max_length=50, verbose_name='单位')),
                ('nianji', models.CharField(default='', max_length=50, verbose_name='年级')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shijuan.PaperList', verbose_name='试卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户总分',
                'verbose_name': '用户总分',
            },
        ),
    ]
