# Generated by Django 2.0 on 2019-08-29 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caozuo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shijuan.Paper', verbose_name='试卷'),
        ),
    ]
