# Generated by Django 2.0 on 2019-08-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nianji',
            field=models.CharField(choices=[('yinianji', '一年级'), ('ernianji', '二年级'), ('sannianji', '三年级')], default='yinianji', max_length=50, verbose_name='年级'),
        ),
    ]
