# Generated by Django 2.0 on 2019-08-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_nianji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='uname',
            new_name='nickname',
        ),
    ]
